apiVersion: 1
datasources:
  - name: TIG-DB
    type: influxdb
    access: proxy
    database: telegraf
    user: telegraf
    password: p#ssw0rd
    url: http://127.0.0.1:48086
    isDefault: true
    editable: true
