apiVersion: 1
datasources:
  - name: TICK-DB
    type: influxdb
    access: proxy
    database: telegraf
    user: admin
    password: admin
    url: http://0.0.0.0:8086
    isDefault: true
    editable: true
